### PR TITLE
don't write software

### PR DESCRIPTION
**Pull request by erikborenstein**
@yoavrand @hanalandes @jghidoni @eyalzaets @jm562  give me some feedback!

### CODE REVIEW

**Comment by yoavrand** [comment]
@erikborenstein , as always - it was a pleasure to read your work. So well written and very relevant for MBAs who are clueless about programming. As someone who is not a native english speaker, I will make my comment carefully (maybe I'm wrong..). I think you misspelled fail, or maybe you used a word which is new to me (fale). :+1:
:us: :us: :us:

**Comment by erikborenstein** [comment]
:scream: great catch @yoavrand

**Comment by eyalzaets** [comment]
Great stuff @erikborenstein. I suggest you never ever write software, stick to what you do best.
Which is... what exactly?
:+1: :+1:

**Comment by erikborenstein** [comment]
@eyalzaets alt text

**Comment by jm562** [comment]
Great agreed... I suggest you never hire me in a programming team! 

:+1: :+1:

**Comment by jghidoni** [comment]
@erikborenstein great takeaway! very true, in particular that the market for developers is very tight right now! :+1: :+1:

**Pull request merged**
