### PR TITLE
Create Hiring-Programmers.md

### PR DESCRIPTION
**Pull request by yoavrand**
This file outlines Yoav Rand's key takeaways from Digital Literacy for Decision Makers class, @eyalzaets @erikborenstein @hanalandes @jghidoni I'd appreciate your feedback!

### CODE REVIEW

**Comment by eyalzaets** [comment]
:+1: :+1:

**Comment by yoavrand** [comment]
@jm562 it's great to have you on board, would love to receive some feedback

**Comment by hanalandes** [comment]
This looks great to me. Substantive material and excellent formatting. :+1:

**Comment by erikborenstein** [comment]
This is so helpful @yoavrand .  I will use this if hiring programmers in the future.  Don't forget to ask them about their strengths and weaknesses.  :+1:

**Comment by yoavrand** [comment]
Thanks everyone for the feedback, I think that my work has matured to the point it is ready to be merged!
:wedding:

**Comment by jm562** [comment]
Ahah been running like a madman all day! Promise to be more useful to the team and in terms of feedback from now on! :+1:

**Pull request merged**
