### PR TITLE
Mobile app development

### PR DESCRIPTION
**Pull request by jghidoni**
Hey team, these are my takeaways on app development. @eyalzaets @erikborenstein @hanalandes @jm562 @yoavrand I'd appreciate your feedback!

### CODE REVIEW

**Comment by hanalandes** [comment]
Thanks for putting this together, @jghidoni. I think it would be help to include brief explanations for each of the thee approaches. A short sentence explaining what each one is, in addition to the current links, would make this file even better!

**Comment by erikborenstein** [comment]
very helpful @jghidoni .  don't forget to optimize your app development for learning! :+1:

**Comment by jm562** [comment]
Great job! :+1:

**Comment by eyalzaets** [comment]
This is the most educating piece I have ever read :exclamation: @jghidoni 
I really liked the way you structured your thoughts around three bullet points. Where did you learn that?
:+1: :+1:

**Comment by yoavrand** [comment]
Great job @jghidoni ! I think it is extremely relevant today, I would also mention that budget might be a big consideration for the approach you choose. :+1: 
:moneybag: :moneybag:

**Comment by jghidoni** [comment]
@hanalandes thanks for the suggestion! I've just added a brief explanation for the technologies. 
@yoavrand great point! budget is definitely one factor to consider, also added it to the file.
@eyalzaets I love to think in a structured way. Let's have an :ice_cream: together, we can discuss more about it!

**Comment by jm562** [comment]
@jghidoni  @eyalzaets  can i suggest we wait on the :ice_cream: given the weather outside and go for something like hot :coffee:  or :tea: .... or alternatively :wine_glass: !

**Pull request merged**
