### PR TITLE
Create Importance-of-Sticky-Notes.md

### PR DESCRIPTION
**Pull request by jm562**
@eyalzaets @yoavrand @jghidoni @hanalandes @erikborenstein 

Guys, took me a little while but also thanks to my IT mentor @jghidoni I finally made it!

### CODE REVIEW

**Comment by jghidoni** [comment]
@jm562 intersting point of view! I'm a big fan of sticky notes :notebook: and to do lists!
:+1: :+1:

**Comment by jm562** [comment]
Ahah... thanks for the :+1:  @jghidoni

**Comment by eyalzaets** [comment]
Great job @jm562 :+1: 
I actually used virtual sticky notes, highly useful for consultants.

**Comment by yoavrand** [comment]
Love it! :+1:

**Comment by hanalandes** [comment]
Sticky notes are the best. Great summary of their versatility! :+1:

**Pull request merged**
