### PR TITLE
Becoming more productive when using computer

### PR DESCRIPTION
**Pull request by eyalzaets**
Hi team,
Would be great if @yoavrand @erikborenstein @hanalandes and @Jghidoni could provide feedback.
Jacopo 2 will follow...

### CODE REVIEW

**Comment by yoavrand** [comment]
I really enjoyed reading your tips about productivity, great work @eyalzaets ! :+1: 
The linked article is also really interesting, I have some experience with that - lmk if you ever want to discuss further.

**Comment by eyalzaets** [comment]
Gee, thanks @yoavrand ! 
Maybe we can discuss this over a beer at happy hour? See you on Thursday!
:pray:

**Comment by yoavrand** [comment]
Sure @eyalzaets !
I'm not drinking :beers: but we can definitely discuss some :computer: scripts over :wine_glass: !

**Comment by eyalzaets** [comment]
@jm562 , please also review and provide feedback. :kiss:

**Comment by jghidoni** [comment]
@eyalzaets a m a z i n g! I'm sure you are already an expert in shortcuts...aren't you a consultant?? :mans_shoe: :briefcase: :office:

**Comment by jghidoni** [comment]
anyway, :+1: :+1: :shipit:

**Comment by hanalandes** [comment]
I really enjoyed reading this @eyalzaets. I was also struck by this takeaway from the class and was looking for some good resources on creating scripts, so thanks for sharing that link! :+1:

**Comment by erikborenstein** [comment]
I wish I knew keyboard shortcuts but for now I will just use the mouse.  Good job @eyalzaets   :+1:

**Comment by jm562** [comment]
@eyalzaets  :+1: :+1: (Especially for the patience!)

**Pull request merged**
