### PR TITLE
Thinking about api communications

### PR DESCRIPTION
**Pull request by hanalandes**
Hey @eyalzaets @erikborenstein @jghidoni @yoavrand @jm562 I'd love your feedback on my note about APIs. Thanks!

### CODE REVIEW

**Comment by yoavrand** [comment]
I really enjoyed reading this @hanalandes !
I'm sure that you will turn into an API expert at Amazon, I'm hoping that in the future I could also leverage your experience for my own online store. :+1: :clap:

**Comment by erikborenstein** [comment]
Great job @hanalandes ! It might be helpful to distinguish between open and closed APIs. Otherwise :+1:

**Comment by eyalzaets** [comment]
Super interesting read! :+1: :+1: 
btw @hanalandes, regarding the LinkedIn article you've shared, I also read about Silicon Valley developers who are campaigning for people to cancel their LinkedIn accounts; they claim one should own his own professional network, and LinkedIn basically blocked one's ability to leverage information from his own network. :trollface:

**Comment by hanalandes** [comment]
Thanks for the feedback, everyone. @eyalzaets, I was talking earlier with @erikborenstein about that same campaign. Super interesting! Perhaps we can discuss it further as a team over :ramen: and :beers:

**Pull request merged**
